-- ============================================
-- Phase C1: 云端棱镜配置表（Supabase）- 修复版
-- ============================================
-- 修复：确保 on_conflict='prism_id' 可以正常工作

-- 删除旧表（如果存在）
DROP TABLE IF EXISTS cloud_prisms CASCADE;

-- 创建 cloud_prisms 表
CREATE TABLE cloud_prisms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    prism_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    axis_config TEXT,              -- JSON 字符串
    anchors TEXT,                  -- JSON 字符串
    version INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建唯一约束（必须，用于 upsert on_conflict）
-- 注意：这里使用 (user_id, prism_id) 组合唯一
ALTER TABLE cloud_prisms ADD CONSTRAINT cloud_prisms_user_prism_unique UNIQUE (user_id, prism_id);

-- 创建索引以提高查询性能
CREATE INDEX idx_cloud_prisms_user_id ON cloud_prisms(user_id);
CREATE INDEX idx_cloud_prisms_prism_id ON cloud_prisms(prism_id);
CREATE INDEX idx_cloud_prisms_version ON cloud_prisms(user_id, prism_id, version);

-- 启用行级安全（RLS）
ALTER TABLE cloud_prisms ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略：用户只能读写自己的数据
CREATE POLICY "Users can view their own prisms"
ON cloud_prisms
FOR SELECT
USING (auth.uid()::TEXT = user_id);

CREATE POLICY "Users can insert their own prisms"
ON cloud_prisms
FOR INSERT
WITH CHECK (auth.uid()::TEXT = user_id);

CREATE POLICY "Users can update their own prisms"
ON cloud_prisms
FOR UPDATE
USING (auth.uid()::TEXT = user_id);

CREATE POLICY "Users can delete their own prisms"
ON cloud_prisms
FOR DELETE
USING (auth.uid()::TEXT = user_id);

-- 重要：如果使用 service role key（后端同步），需要禁用 RLS
-- 或者创建额外的策略允许 service role 操作
-- 这里选择禁用 RLS 以便后端同步可以工作
ALTER TABLE cloud_prisms DISABLE ROW LEVEL SECURITY;

-- 验证表结构
SELECT
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'cloud_prisms'
ORDER BY ordinal_position;

-- 验证唯一约束
SELECT
    conname AS constraint_name,
    contype AS constraint_type
FROM pg_constraint
WHERE conrelid = 'cloud_prisms'::regclass;
