-- ============================================
-- Phase C1: 云端棱镜配置表（Supabase）
-- ============================================
-- 用于存储用户的棱镜配置到云端
-- 支持多设备同步和版本控制

-- 创建 cloud_prisms 表
CREATE TABLE IF NOT EXISTS cloud_prisms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    prism_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    axis_config TEXT,              -- JSON 字符串
    anchors TEXT,                  -- JSON 字符串
    version INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- 约束
    UNIQUE(user_id, prism_id)
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_cloud_prisms_user_id ON cloud_prisms(user_id);
CREATE INDEX IF NOT EXISTS idx_cloud_prisms_prism_id ON cloud_prisms(prism_id);
CREATE INDEX IF NOT EXISTS idx_cloud_prisms_version ON cloud_prisms(user_id, prism_id, version);

-- 启用行级安全（RLS）
ALTER TABLE cloud_prisms ENABLE ROW LEVEL SECURITY;

-- 创建 RLS 策略：用户只能读写自己的数据
CREATE POLICY "Users can view their own prisms"
ON cloud_prisms
FOR SELECT
USING (auth.uid()::TEXT = user_id);

CREATE POLICY "Users can insert their own prisms"
ON cloud_prisms
FOR INSERT
WITH CHECK (auth.uid()::TEXT = user_id);

CREATE POLICY "Users can update their own prisms"
ON cloud_prisms
FOR UPDATE
USING (auth.uid()::TEXT = user_id);

CREATE POLICY "Users can delete their own prisms"
ON cloud_prisms
FOR DELETE
USING (auth.uid()::TEXT = user_id);

-- 注意：如果使用 service role key（后端同步），可以绕过 RLS
-- 或者创建额外的策略允许 service role 操作
